format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
[â”‚](bold green)$directory$git_branch$git_status$nodejs$php
[â””â”€>](bold green) """

[directory]
style = "blue bold"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "ğŸŒ± "
style = "bold purple"

[git_status]
style = "red bold"

[nodejs]
symbol = "â¬¢ "
style = "bold green"
format = "via [$symbol($version )]($style)"

[php]
symbol = "ğŸ˜ "
style = "bold blue"
format = "via [$symbol($version )]($style)"